#!/bin/sh

help() { cat <</help
Usage: $0 [FLASHES]
  FLASHES       The number of times to flash the screen (default=1)
/help
}

# Usage: missing COMMAND [COMMAND...]
# True if given command(s) are missing
missing() {
  ! command -v "$@" >/dev/null 2>&1
}

# Usage: die [ERROR_MESSAGE...]
# Report given error and exit
die() {
  echo "$0: $*" >&2
  exit 2
}

# Usage: usleep
# Wait 100ms (falls back to perl if `sleep` doesn't support decimals)
usleep() {
  sleep 0.1 2>/dev/null \
    || perl -e 'use Time::HiRes "usleep"; usleep(100000)' 2>/dev/null
}

# the number of flashes defaults to one
FLASHES=1

# parse arguments
if [ $# -gt 0 ]; then

  # -h and --help (and -help and -hello, for that matter)
  if [ "${1#-h}" != "${1#--help}" ]; then
    help
    exit
  elif [ "$1" -gt 0 ] 2>/dev/null; then
    FLASHES="$1"
  else
    die "Invalid number of flashes '$1'"
  fi

fi

if missing xvisbell; then
  # maybe it's in the same place as this script but not yet in the path
  relative="${0%/*}/xvisbell"
  if [ -x "$relative" ]; then
    xvisbell() { "$relative" ${1+"$@"}; }
  else
    die "Error, missing 'xvisbell' command"
  fi
fi

if missing xkbbell; then
  die "Error, missing 'xkbbell' (part of xkbutils or x11-xkb-utils)"
fi


while [ ${FLASHES:=1} -gt 0 ]; do

  xvisbell --once &
  usleep
  xkbbell

  FLASHES=$((FLASHES-1))

  if [ $FLASHES -gt 0 ]; then
    usleep
  fi

done
